# Xbox/Xbox360 USB Gamepad Userspace Driver
# Copyright (C) 2008 Ingo Ruhnke <grumbel@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Build file for https://travis-ci.org/
#
# Configuration manual:
# http://docs.travis-ci.com/user/build-configuration/

language: cpp

compiler:
  - gcc
  - clang

matrix:
  fast_finish: true

env:
  matrix:
    - BUILD_TYPE="development"
    - BUILD_TYPE="release"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential scons g++ scons pkg-config libusb-1.0-0-dev libx11-dev libudev-dev x11proto-core-dev libdbus-glib-1-dev

script:
  - git clean -f
  - scons CXX=${CXX} BUILD=${BUILD_TYPE} && sudo make install
  - sudo make install

# EOF #
